# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-20 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jibbrjabbrmain', '0002_jjstory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jjstory',
            old_name='URL',
            new_name='storyURL',
        ),
        migrations.AddField(
            model_name='jjstory',
            name='storyTitle',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
