# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-20 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jibbrjabbrmain', '0003_auto_20191220_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='jjstory',
            name='storyImg',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
